### ISSUE TITLE
Potential Bug with Input/Output Mixing

### ISSUE THREAD

**Issue by mackncheesiest** [mackncheesiest/ECE474A_Projects#1]
I think there might be an issue [here](https://github.com/mackncheesiest/ECE474A_Projects/blob/618fd86cefb3e59237ecd949a33a6977bba42f53/Assignment2/Solution/sources/Parser.cpp#L219) if the input and output declarations alternate in the source netlist file. 

It would appear that Nets::getIOListString() doesn't really care if it mixes inputs and outputs together on the same line

**Comment by kennondmckeever** [comment]
I think this line is for the ports of the module. Each Input/Output/Wire gets its own line within the module when it gets declared.
Let me know if you think this is an issue, but based on the output I've seen so far, I don't think this is anything to worry about

**Comment by mackncheesiest** [comment]
Oh, I see, yeah, this is only for the "module(a, b, c, d, Clk, Rst)" type ports. Yeah, then this shouldn't be a problem then.

**Comment by kennondmckeever** [comment]
The IO names list is the list of ports to the module, whereas the IO
declarations list is the list of lines like "output[7:0] myOutput;"
That said, is there still an issue here? Or were you concerned it would do
something like "output[7:0] myOutput, myInput;" in the declaration of a net?

**Comment by mackncheesiest** [comment]
I was concerned about the latter -- doing something like "output [7:0] myOutput, myInput;"
