### ISSUE TITLE
Modify the outputs of the Parser to say "variable" instead of "wire"

### ISSUE THREAD

**Issue by scottmarshall17** [mackncheesiest/ECE474A_Projects#17]

**Comment by kennondmckeever** [comment]
what exactly did we mean by this? I think it's handled properly now, but correct me if I'm wrong. (I.E. let me know if it's what is causing errors when scheduling

**Comment by scottmarshall17** [comment]
Some test cases seem to be passing. The preprocessed file I believe was spitting out 'wire' instead of 'variable' so the parser was having trouble with that since the assignment docs changed the file format a bit.
