### ISSUE TITLE
Infinite loop with low latency constraint

### ISSUE THREAD

**Issue by kennondmckeever** [mackncheesiest/ECE474A_Projects#20]
I called $ ./hlsyn hls_lat_test4.c 3 test_output.v

Console Output:
========testing hls_lat_test4.c=======
I scheduled sink MUL in cycle 2
I scheduled sink ADD in cycle 3
I scheduled ADD in cycle 2
I scheduled ADD in cycle 1
I scheduled MUL in cycle 0
Finished with ALAP!
There are 2 sinks in this graph
I'm starting the main List_R loop
-  -  -  -  -  -  -  -  -  -  -  -  -  -  -  

Considering schedule for component ADD in cycle 1
There are 1 zero slack operations and 0 nonzero slack operations
I scheduled ADD in cycle 1

Considering schedule for component SUB in cycle 1
There are 0 zero slack operations and 0 nonzero slack operations

Considering schedule for component MUL in cycle 1
There are 1 zero slack operations and 0 nonzero slack operations
I scheduled MUL in cycle 1

Considering schedule for component MUX2x1 in cycle 1
There are 0 zero slack operations and 0 nonzero slack operations

Considering schedule for component REG in cycle 1
There are 0 zero slack operations and 0 nonzero slack operations

Considering schedule for component SHR in cycle 1
There are 0 zero slack operations and 0 nonzero slack operations

Considering schedule for component SHL in cycle 1
There are 0 zero slack operations and 0 nonzero slack operations

Considering schedule for component COMP in cycle 1
There are 0 zero slack operations and 0 nonzero slack operations

Time step is now 2
The graph sink schedule status is: 0
Considering schedule for component ADD in cycle 2
There are 1 zero slack operations and 0 nonzero slack operations
I scheduled ADD in cycle 2

Considering schedule for component SUB in cycle 2
There are 0 zero slack operations and 0 nonzero slack operations

Considering schedule for component MUL in cycle 2
There are 0 zero slack operations and 0 nonzero slack operations

Considering schedule for component MUX2x1 in cycle 2
There are 0 zero slack operations and 0 nonzero slack operations

Considering schedule for component REG in cycle 2
There are 0 zero slack operations and 0 nonzero slack operations

Considering schedule for component SHR in cycle 2
There are 0 zero slack operations and 0 nonzero slack operations

Considering schedule for component SHL in cycle 2
There are 0 zero slack operations and 0 nonzero slack operations

Considering schedule for component COMP in cycle 2
There are 0 zero slack operations and 0 nonzero slack operations

Time step is now 3
The graph sink schedule status is: 0
Considering schedule for component ADD in cycle 3
There are 1 zero slack operations and 0 nonzero slack operations
I scheduled ADD in cycle 3

Considering schedule for component SUB in cycle 3
There are 0 zero slack operations and 0 nonzero slack operations

Considering schedule for component MUL in cycle 3
There are 1 zero slack operations and 0 nonzero slack operations
I scheduled MUL in cycle 3

Considering schedule for component MUX2x1 in cycle 3
There are 0 zero slack operations and 0 nonzero slack operations

Considering schedule for component REG in cycle 3
There are 0 zero slack operations and 0 nonzero slack operations

Considering schedule for component SHR in cycle 3
There are 0 zero slack operations and 0 nonzero slack operations

Considering schedule for component SHL in cycle 3
There are 0 zero slack operations and 0 nonzero slack operations

Considering schedule for component COMP in cycle 3
There are 0 zero slack operations and 0 nonzero slack operations

Time step is now 4
The graph sink schedule status is: 1
I am about to delete numComponents
I am about to delete componentsAvailable
Donezo, gg List_R
Node ADD with inputs {a}, {b},  is List_R scheduled in cycle 1
Node ADD with inputs {h}, {c},  is List_R scheduled in cycle 2
Node ADD with inputs {i}, {d},  is List_R scheduled in cycle 3
Node MUL with inputs {e}, {f},  is List_R scheduled in cycle 1
Node MUL with inputs {k}, {g},  is List_R scheduled in cycle 3
Module name 'hls_lat_test4.c' inferred from input file 'hls_lat_test4.c.txt' is invalid. Module will be renamed 'myModule'
0
1
2
0
2
Finished Parser::generate()

testing hls_lat_test5.c
I scheduled sink MUL in cycle 2
I scheduled sink MUL in cycle 2
I scheduled ADD in cycle 1
I scheduled MUL in cycle -1
I scheduled MUL in cycle -1
I scheduled MUL in cycle -1
I scheduled MUL in cycle -1
I scheduled MUL in cycle -1

**Comment by mackncheesiest** [comment]
Probably closed when modifications were made to quit when ALAP fails somewhere around c0a19f52453d532e1862c92f57de921a5515c16e
