### ISSUE TITLE
Registers not always generated

### ISSUE THREAD

**Issue by kennondmckeever** [mackncheesiest/ECE474A_Projects#4]
In some of the output files, registers are not generated when they should be. This is likely an issue with Parser::ParseLine(). 
Note: I've also noticed that shifters are not generated for circuit 5, but I think it's because of this problem.

**Comment by mackncheesiest** [comment]
Which test file in particular generates this?

**Comment by kennondmckeever** [comment]
In particular, circuit 1 and circuit 5. But the TA also said (randomly, on Piazza) that ALL outputs must implicitly be registers anyway, so I've found a workaround that I'm about to push

**Comment by kennondmckeever** [comment]
Hmm... So I think I fixed this now for the most part, but I noticed that our code isn't capable of creating a register out of thin air like Tosi specified. For example:
```
input Int8 a, b, c
register Int8 t
wire Int8 v
output Int8 z

t = a * b
v = c * t
z = v
```
In this code, t should be assigned to the input AND output of a register, somehow.

**Comment by mackncheesiest** [comment]
Wasn't that piece commented out at some point in Parser::parse()?

It prints a message to the console instead iirc

**Comment by mackncheesiest** [comment]
Around [here](https://github.com/mackncheesiest/ECE474A_Projects/blob/cb97f0d6d2d7da7079e7eab313f76c87199af37c/Assignment2/Solution/sources/Parser.cpp#L83)

Oh I see, you were trying to make that work.

**Comment by kennondmckeever** [comment]
Yeah, I think it works now for the first 5 circuits, but it isn't able to use one 'net' name as both the input and output of a register as stated in the assignment spec.

**Comment by mackncheesiest** [comment]
What's the status of this?

**Comment by kennondmckeever** [comment]
Not sure. I think it works, but we should still test it.

**Comment by mackncheesiest** [comment]
Not sure where this was fixed, but it was fixed at some point judging off of our testing before submission.
