### ISSUE TITLE
Need to Quit When Errors Occur

### ISSUE THREAD

**Issue by mackncheesiest** [mackncheesiest/ECE474A_Projects#9]
If errors occur in the parsing (i.e. wires don't exist and are used in an operation), our program doesn't crash

**Comment by kennondmckeever** [comment]
It can quit when errors occur, but it displays all of the errors that it finds, and doesn't just quit after one. Maybe it should quit after the first error; I guess we could look into the assignment spec to see if a preferred behavior is specified.

**Comment by kennondmckeever** [comment]
This is still an issue for us if it runs into an unrecognized operator

**Comment by kennondmckeever** [comment]
Nevermind, I think this is all good.
